function createfigure(X1, Y1, S1, C1, X2, Y2, C2, Y3, Y4, Y5, Y6)
%CREATEFIGURE(X1, Y1, S1, C1, X2, Y2, C2, Y3, Y4, Y5, Y6)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X2:  scatter x
%  Y2:  scatter y
%  C2:  scatter c
%  Y3:  scatter y
%  Y4:  scatter y
%  Y5:  scatter y
%  Y6:  scatter y

%  Auto-generated by MATLAB on 18-Jan-2019 13:33:31

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'Parent',subplot1,'Marker','*');

% Create ylabel
ylabel(['Minimum Distance';'to Pedestrian(m)'],'FontSize',18);

% Create title
title('Rightmost Lane','FontSize',18);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 13]);
grid(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',12);
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.50266296276652 0.709264705882353 0.334659090909091 0.215735294117647]);
hold(axes1,'on');

% Create scatter
scatter(X2,Y2,S1,C2,'Parent',axes1);

% Create title
title('Second to Right Lane','FontSize',18);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 9]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.127666277712952 0.458466981132076 0.33465909090909 0.215735294117647]);
hold(axes2,'on');

% Create scatter
scatter(X1,Y3,S1,C1,'Parent',axes2,'Marker','*');

% Create ylabel
ylabel(['Average       ';'Velocity (m/s)'],'FontSize',18);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 5]);
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',12);
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.502662962766521 0.456247225305216 0.334659090909091 0.215735294117647]);
hold(axes3,'on');

% Create scatter
scatter(X2,Y4,S1,C2,'Parent',axes3);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 5]);
grid(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontSize',12);
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.128833138856476 0.204339622641509 0.334659090909091 0.215735294117647]);
hold(axes4,'on');

% Create scatter
scatter(X1,Y5,S1,C1,'Parent',axes4,'Marker','*');

% Create ylabel
ylabel(['Maximum             ';'Acceleration (m/s^2)'],'FontSize',18);

% Create xlabel
xlabel(['Pedestrian      ';'Accepted Gap (s)'],'FontSize',18);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 9]);
grid(axes4,'on');
% Set the remaining axes properties
set(axes4,'FontSize',12);
% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.501496101622997 0.20322974472808 0.33465909090909 0.215735294117647]);
hold(axes5,'on');

% Create scatter
scatter(X2,Y6,S1,C2,'Parent',axes5);

% Create xlabel
xlabel(['Pedestrian      ';'Accepted Gap (s)'],'FontSize',18);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0 9]);
grid(axes5,'on');
% Set the remaining axes properties
set(axes5,'FontSize',12);
